public enum MessageType
{
	CLIENTSHUTDOWN,
	CLIENTREQUESTMAP,
	SERVERSHUTDOWN,
	SERVERPOLL,
	MATCHINPROGRESS,
	SERVERSTARTGAME,
	CLIENTTIMEOUT,
	CLIENTCHANGETEAM,
	SERVERUPDATETEAM,
	SERVERUPDATEMAP,
	TEXTMESSAGE,
	NAMEMESSAGE,
	SERVERUPDATENAMES
}
